name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.21"
          - "1.20"
          - "1.19"
          - "1.18"
        goexperiment: [""]
        include:
          # test with GOEXPERIMENT=loopvar
          # https://github.com/golang/go/wiki/LoopvarExperiment
          - os: ubuntu-latest
            go: "1.21"
            goexperiment: "loopvar"

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: test
        run: |
          go test -v -coverprofile=profile.cov ./...
        env:
          GOEXPERIMENT: ${{ matrix.goexperiment }}

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          flag-name: Go-${{ matrix.go }}
          parallel: true

  # notifies that all test jobs are finished.
  finish:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
